/**
 * Passage of the Day data
 * 100 foundational passages for disciples (5-12 verses each)
 *
 * TODO: Add 100 more passages before launch to cover full year with variety
 */

import type { PassageOfTheDay } from '@/types/journal';
import { parseReferenceToUSFM } from './bibleData';

// ============================================
// PASSAGES DATA (100 entries)
// ============================================

export const PASSAGES: PassageOfTheDay[] = [
  // Shuffled order for daily variety - mixes categories throughout the year
  { reference: "Ephesians 1:3-10", theme: "Blessed in Christ", category: "identity", explanation: "Before you were born, God chose you to be His. Every spiritual blessing you could ever need is already yours in Christ—not because you earned it, but because God decided to lavish His grace on you. This passage is about your identity: you are blessed, chosen, adopted, and redeemed. You don't have to work to become these things; you already are because of Jesus." },
  { reference: "John 3:14-21", theme: "God So Loved the World", category: "salvation", explanation: "God didn't send Jesus to condemn you—He sent Jesus to save you. The world was already condemned by sin, but Jesus came to rescue you from that. Believing in Jesus isn't about being good enough; it's about trusting that what He did on the cross was enough to save you. God's love for you is the reason Jesus came, not your performance." },
  { reference: "Psalm 23:1-6", theme: "The Lord Is My Shepherd", category: "trust", explanation: "God is like a shepherd who takes care of everything you need. When you're walking through hard times (\"the valley of the shadow of death\"), He's right there with you—not waiting for you at the end, but walking through it with you. You don't have to be afraid because God is your protector, provider, and guide. His goodness and love follow you every single day of your life." },
  { reference: "1 Corinthians 13:1-13", theme: "The Way of Love", category: "love", explanation: "You can have spiritual gifts, knowledge, faith, and generosity, but without love, it all means nothing. Real love isn't just a feeling—it's patient, kind, and doesn't keep track of wrongs. This is how God loves you, and it's how He wants you to love others. Love never fails because God never fails, and He is love." },
  { reference: "Hebrews 11:1-10", theme: "By Faith", category: "faith", explanation: "Faith is being confident in what you hope for even when you can't see it yet. The people in this passage (like Abraham) trusted God's promises before they saw them come true. Faith isn't pretending everything is fine—it's believing God is who He says He is and will do what He says He'll do. God is pleased when you trust Him, even when life doesn't make sense." },
  { reference: "John 14:15-26", theme: "The Spirit of Truth", category: "spirit", explanation: "Jesus didn't leave you alone to figure life out. He sent the Holy Spirit to live inside you, teach you, and remind you of truth. The Spirit is your Advocate—someone who is always on your side, helping you. When you feel confused or don't know what to do, the Holy Spirit is there to guide you into truth and peace." },
  { reference: "Matthew 5:3-12", theme: "The Beatitudes", category: "teaching", explanation: "Jesus turns the world's values upside down. The world says be strong, confident, and powerful—but Jesus says the humble, merciful, and pure in heart are blessed. Being blessed doesn't mean your life is easy; it means you belong to God's kingdom. Even when you're persecuted or going through hard times, God sees you, and you are blessed because you're His." },
  { reference: "Romans 12:1-8", theme: "Living Sacrifices", category: "surrender", explanation: "Because of God's mercy (everything He's already done for you), you can offer your life back to Him—not to earn His love, but as a response to it. Don't let the world shape how you think; let God renew your mind so you see yourself the way He does. You have unique gifts and a unique role in the body of Christ—use them to serve others, not to prove your worth." },
  { reference: "Philippians 4:4-9", theme: "Pray About Everything", category: "prayer", explanation: "You can rejoice always because the Lord is near—not far away waiting for you to get your act together. When anxiety hits, don't try to handle it alone; pray about it and let God's peace guard your heart. God's peace doesn't always make sense (it \"surpasses understanding\"), but it's real and available to you when you bring your worries to Him." },
  { reference: "Ephesians 6:10-18", theme: "The Armor of God", category: "warfare", explanation: "You're in a spiritual battle, but you don't fight in your own strength. God gives you armor—truth, righteousness, the gospel of peace, faith, salvation, and His Word. You're not fighting for victory; you're fighting from victory because Jesus already won. Stand firm in what Christ has done, not in what you can do." },

  { reference: "Romans 8:1-11", theme: "Life in the Spirit", category: "identity", explanation: "There is now no condemnation for those who are in Christ Jesus. That means God isn't holding your mistakes against you—the penalty for sin was paid by Jesus. You're not controlled by your sinful nature anymore; the Spirit of God lives in you. Living by the Spirit means letting Him lead you, not trying to prove yourself through rule-following." },
  { reference: "Romans 3:21-28", theme: "Justified by Faith", category: "salvation", explanation: "You are made right with God through faith in Jesus, not by following rules perfectly. Everyone has sinned and fallen short of God's glory—no one is good enough on their own. But God's grace is a free gift, and Jesus paid the price to make you righteous. You can't earn salvation; you can only receive it by trusting what Jesus did." },
  { reference: "Psalm 46:1-11", theme: "God Is Our Refuge", category: "trust", explanation: "When everything feels like it's falling apart, God is your safe place. You don't have to be afraid because God is with you, no matter what chaos is happening around you. Even when nations rage and kingdoms fall, God is your refuge and strength. \"Be still and know that I am God\"—sometimes the strongest thing you can do is rest in His presence." },
  { reference: "1 John 4:7-16", theme: "God Is Love", category: "love", explanation: "Love comes from God—it's not something you manufacture on your own. God showed His love by sending Jesus to die for you while you were still a sinner. Because God first loved you, you can love others. Love isn't just a feeling you try to muster up; it's the overflow of receiving God's love for you." },
  { reference: "Hebrews 11:32-40", theme: "Heroes of Faith", category: "faith", explanation: "These heroes of faith conquered kingdoms, shut the mouths of lions, and saw miracles—but some were tortured, persecuted, and killed. Faith doesn't guarantee an easy life, but it guarantees God's presence in every circumstance. All these people were commended for their faith, even though they didn't see all of God's promises fulfilled in their lifetime. Your faith matters even when you can't see the full picture yet." },
  { reference: "John 16:5-15", theme: "The Spirit Will Guide You", category: "spirit", explanation: "Jesus told His disciples it was actually better for Him to leave so the Holy Spirit could come. The Spirit convicts the world of sin, guides you into all truth, and glorifies Jesus. You're not left to figure out life on your own—the Spirit is with you, teaching you and reminding you of everything Jesus said. He's your constant companion and guide." },
  { reference: "Matthew 5:13-20", theme: "Salt and Light", category: "teaching", explanation: "You are the salt of the earth and the light of the world—not because you're trying to be, but because Christ lives in you. Salt preserves and adds flavor; light exposes darkness. You don't have to force yourself to shine; you shine naturally when you live in the freedom Jesus gave you. Don't hide who you are in Christ—let your light shine so others can see God's goodness." },
  { reference: "Philippians 2:1-11", theme: "The Mind of Christ", category: "humility", explanation: "Jesus, who was God, didn't cling to His position or power—He humbled Himself and became a servant. This is the attitude you're invited to have: thinking of others, not just yourself. You don't serve to earn God's favor; you serve because Christ already humbled Himself for you. True greatness in God's kingdom looks like Jesus washing His disciples' feet." },
  { reference: "Colossians 4:2-6", theme: "Devote Yourselves to Prayer", category: "prayer", explanation: "Prayer isn't just something you do when you're in trouble—it's an ongoing conversation with God. Be watchful and thankful as you pray, and ask God to open doors for sharing the gospel. The way you live and speak should point people to Jesus. Prayer keeps you connected to God's heart and mission." },
  { reference: "2 Corinthians 10:3-6", theme: "Divine Power", category: "warfare", explanation: "You're in a real spiritual battle, but you don't fight with human weapons. God gives you divine power to demolish arguments and lies that oppose Him. The battlefield is in your mind—where lies try to take root. You have the authority in Christ to take every thought captive and make it obedient to Him." },

  { reference: "Romans 8:28-39", theme: "More Than Conquerors", category: "identity", explanation: "God works everything together for good for those who love Him—even the hard, painful, confusing things. Nothing can separate you from God's love: not trouble, hardship, persecution, or even death. You are more than a conqueror through Jesus, which means the victory is already yours. If God is for you, who can be against you?" },
  { reference: "Romans 5:1-11", theme: "Peace with God", category: "salvation", explanation: "You have peace with God through Jesus—not because you achieved perfection, but because Jesus paid the price. While you were still a sinner, Christ died for you. That's how much God loves you: He didn't wait for you to clean up your life first. You can rejoice even in suffering because it produces perseverance, character, and hope that won't disappoint you." },
  { reference: "Psalm 27:1-8", theme: "The Lord Is My Light", category: "trust", explanation: "When you're afraid, God is your light and salvation—there's nothing to fear when the Creator of the universe is on your side. The one thing David wanted more than anything was to dwell in God's presence. You don't have to perform to be in God's presence; you're invited to seek His face and rest in His protection." },
  { reference: "John 15:9-17", theme: "Remain in My Love", category: "love", explanation: "Jesus loves you the same way the Father loves Him—that's an unshakeable, unchanging love. You remain in His love by trusting Him, not by earning it. Jesus calls you His friend, not His servant, because He's chosen to share everything with you. Love each other the way Jesus loved you: sacrificially and without condition." },
  { reference: "James 2:14-26", theme: "Faith and Works", category: "faith", explanation: "Real faith isn't just believing the right things in your head—it changes how you live. Works don't save you, but genuine faith will naturally produce good works. If someone says they have faith but their life shows no evidence of it, that faith is dead. You're saved by grace through faith, and that living faith will show itself in love and action." },
  { reference: "Acts 2:1-12", theme: "The Day of Pentecost", category: "spirit", explanation: "The Holy Spirit came with power on the day of Pentecost, just as Jesus promised. The disciples were filled with the Spirit and began speaking in different languages so everyone could hear the gospel. This wasn't just a one-time event—the same Spirit that empowered the early church lives in you. God gives His Spirit to empower you for His mission." },
  { reference: "Matthew 5:38-48", theme: "Love Your Enemies", category: "teaching", explanation: "Jesus calls you to love your enemies and pray for those who persecute you. This goes against everything the world teaches about revenge and getting even. When you love your enemies, you reflect your Father in heaven who shows kindness to everyone. You're not called to be a doormat, but you are called to respond with love instead of hate." },
  { reference: "Philippians 3:7-14", theme: "Press On Toward the Goal", category: "growth", explanation: "Paul counted everything as loss compared to knowing Christ. All his achievements, credentials, and rule-following meant nothing compared to the righteousness that comes through faith in Jesus. You're not trying to reach perfection; you're pressing on because Christ has already taken hold of you. Forget what's behind (your failures and successes) and press toward the goal of knowing Christ more." },
  { reference: "1 Thessalonians 5:16-24", theme: "Pray Continually", category: "prayer", explanation: "Rejoice always, pray continually, and give thanks in all circumstances. This doesn't mean fake positivity—it means trusting God is with you no matter what. Prayer isn't just a morning or bedtime activity; it's an ongoing conversation with God throughout your day. God is faithful and will complete the good work He started in you." },
  { reference: "James 4:6-10", theme: "Resist the Devil", category: "warfare", explanation: "God opposes the proud but gives grace to the humble. When you humble yourself before God and resist the devil, he will flee from you. Draw near to God, and He will draw near to you. Humility isn't thinking less of yourself; it's recognizing your complete dependence on God's grace." },

  { reference: "Colossians 3:1-11", theme: "Raised with Christ", category: "identity", explanation: "You've been raised with Christ, so set your heart on things above, not earthly things. You died to your old life, and your new life is hidden with Christ in God. This means your identity is no longer defined by your past, your performance, or what others think. You're being renewed in the image of God, becoming who you were always meant to be." },
  { reference: "Romans 6:1-11", theme: "Dead to Sin, Alive in Christ", category: "salvation", explanation: "Should you keep sinning so grace can increase? Absolutely not! You died to sin when you were baptized into Christ. Your old self was crucified with Him so you're no longer a slave to sin. You're not trying to become dead to sin—you already are. Now live like it's true, because it is." },
  { reference: "Psalm 37:1-9", theme: "Trust in the Lord", category: "trust", explanation: "Don't stress out when you see evil people succeed. Trust in the Lord and do good, and He will give you the desires of your heart. Be patient and wait for God's timing—don't take matters into your own hands. The meek (those who trust God) will inherit the land, not those who fight and scheme for power." },
  { reference: "Romans 12:9-21", theme: "Love in Action", category: "love", explanation: "Love must be sincere—not fake or manipulative. Hate what is evil and cling to what is good. Don't seek revenge when someone wrongs you; instead, overcome evil with good. When your enemy is hungry, feed him. This kind of love is only possible when you're living from God's love for you." },
  { reference: "Romans 4:18-25", theme: "Abraham's Faith", category: "faith", explanation: "Abraham believed God's promise even when it seemed impossible. He didn't waver in unbelief but was strengthened in his faith, giving glory to God. He was fully convinced that God could do what He promised. Your faith is credited as righteousness the same way—not because you're perfect, but because you trust the One who raised Jesus from the dead." },
  { reference: "Galatians 5:16-26", theme: "Fruit of the Spirit", category: "spirit", explanation: "Walk by the Spirit, and you won't gratify the desires of the flesh. The flesh and Spirit are in opposition to each other. But the fruit of the Spirit—love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control—grows naturally when you're connected to Jesus. You don't produce fruit by trying harder; you produce it by abiding in Christ." },
  { reference: "Matthew 6:5-15", theme: "How to Pray", category: "prayer", explanation: "Don't pray to be seen by others or to impress God with fancy words. Go to your private place and talk to your Father, who sees what you do in secret. Pray simply and honestly. Forgive others when you pray, because you've been forgiven. Prayer isn't about performing; it's about relationship with God." },
  { reference: "Colossians 1:9-14", theme: "Walk Worthy of the Lord", category: "growth", explanation: "Paul prayed that the Colossians would be filled with the knowledge of God's will so they could walk in a manner worthy of the Lord. You have the strength to endure anything through God's glorious power. He has rescued you from the kingdom of darkness and brought you into the kingdom of His Son. You're already in the right kingdom; now walk like it." },
  { reference: "James 5:13-18", theme: "The Prayer of Faith", category: "prayer", explanation: "When you're in trouble, pray. When you're happy, sing. When you're sick, call the elders to pray over you. The prayer of a righteous person is powerful and effective. You're righteous because of Jesus, so your prayers matter. God hears you and responds—sometimes in ways you expect, sometimes in ways you don't." },
  { reference: "Matthew 28:16-20", theme: "The Great Commission", category: "mission", explanation: "Jesus has all authority in heaven and on earth, and He sends you out to make disciples. You're not going alone—He promises to be with you always. Making disciples isn't just for pastors or missionaries; it's for everyone who follows Jesus. Baptize people and teach them to obey everything Jesus commanded. He's with you every step of the way." },

  { reference: "2 Corinthians 5:14-21", theme: "New Creation", category: "identity", explanation: "If anyone is in Christ, the new creation has come—the old has gone, the new is here! God reconciled you to Himself through Christ and gave you the ministry of reconciliation. You're not defined by your past anymore. You're a new creation, and God sees you as righteous because of Jesus. This isn't something you're trying to become; this is who you already are." },
  { reference: "Titus 3:3-8", theme: "Saved by His Mercy", category: "grace", explanation: "You were once foolish, disobedient, and enslaved by passions—but God saved you by His mercy, not because of righteous things you did. He washed you clean through the Holy Spirit, whom He poured out on you generously. You're justified by His grace and are heirs of eternal life. This is all God's doing, not yours." },
  { reference: "Psalm 91:1-12", theme: "Under His Wings", category: "protection", explanation: "When you dwell in the shelter of the Most High, you rest in His shadow. God is your refuge and fortress—the One you can trust completely. He covers you with His feathers, and under His wings you find safety. No harm can come to you that hasn't passed through His hands first. God protects you, not because you're perfect, but because you're His." },
  { reference: "Colossians 3:12-17", theme: "Clothe Yourselves with Love", category: "love", explanation: "As God's chosen people, clothe yourselves with compassion, kindness, humility, gentleness, and patience. Bear with each other and forgive as the Lord forgave you. Above all, put on love, which binds everything together in perfect unity. Let the peace of Christ rule in your hearts. You can live this way because you're already chosen and loved by God." },
  { reference: "Mark 11:22-26", theme: "Have Faith in God", category: "faith", explanation: "Jesus says to have faith in God—the kind of faith that moves mountains. When you pray, believe that you've already received what you ask for. But also, when you stand praying, forgive anyone you have something against. Faith works through love and forgiveness. Unforgiveness blocks your prayers—not because God stops loving you, but because bitterness closes your heart." },
  { reference: "Romans 8:12-17", theme: "Led by the Spirit", category: "spirit", explanation: "You're not obligated to live by your sinful nature anymore. The Spirit leads you as a child of God. You didn't receive a spirit of slavery to fear, but the Spirit of adoption—you can call God \"Abba, Father.\" You're an heir of God and co-heir with Christ. The Spirit testifies that you belong to God's family." },
  { reference: "Matthew 6:25-34", theme: "Do Not Worry", category: "trust", explanation: "Don't worry about your life—what you'll eat, drink, or wear. God feeds the birds and clothes the flowers; you're worth much more than these. Worrying doesn't add a single hour to your life. Seek God's kingdom first, and He'll take care of everything else you need. You have a Father who knows what you need before you ask." },
  { reference: "1 Thessalonians 4:1-8", theme: "Living to Please God", category: "holiness", explanation: "Live to please God more and more—not to earn His love, but because you already have it. God's will is your sanctification (being set apart for Him). Control your body in holiness, not in lustful passion. God didn't call you to impurity but to holiness. You can live holy because the Holy Spirit lives in you." },
  { reference: "Proverbs 3:1-8", theme: "Trust in the Lord", category: "wisdom", explanation: "Trust in the Lord with all your heart and don't lean on your own understanding. In all your ways acknowledge Him, and He'll direct your paths. Don't be wise in your own eyes; fear the Lord and turn away from evil. Trusting God doesn't mean you turn off your brain—it means you recognize His wisdom is greater than yours." },
  { reference: "Acts 1:4-11", theme: "You Will Be My Witnesses", category: "mission", explanation: "Jesus told His disciples to wait for the Holy Spirit, who would give them power to be His witnesses. You're not supposed to spread the gospel in your own strength. The Spirit empowers you to tell others about Jesus. You'll be His witness wherever you are—starting where you live and extending to the ends of the earth." },

  { reference: "Galatians 2:15-21", theme: "Crucified with Christ", category: "identity", explanation: "You're justified by faith in Christ, not by works of the law. You've been crucified with Christ, and you no longer live—Christ lives in you. The life you now live, you live by faith in the Son of God who loved you and gave Himself for you. Your identity is completely wrapped up in Jesus, not in what you do." },
  { reference: "1 John 1:5-10", theme: "Walking in the Light", category: "grace", explanation: "God is light, and in Him there is no darkness. If you walk in the light as He is in the light, you have fellowship with one another and the blood of Jesus purifies you from all sin. If you claim to be without sin, you're deceiving yourself. But if you confess your sins, God is faithful to forgive and cleanse you. Walking in the light doesn't mean being perfect; it means being honest about your need for Jesus." },
  { reference: "Psalm 121:1-8", theme: "My Help Comes from the Lord", category: "trust", explanation: "Where does your help come from? From the Lord, who made heaven and earth. He won't let your foot slip, and He never sleeps or gets tired of watching over you. The Lord is your keeper and protector from all harm. Your help doesn't come from your own strength or resources—it comes from the God who never stops caring for you." },
  { reference: "John 1:1-14", theme: "The Word Became Flesh", category: "jesus", explanation: "Jesus is the Word who was with God in the beginning—He is God. Through Him all things were made, and in Him is life and light. The Word became flesh and lived among us. He came to His own people, but many didn't receive Him. But to those who did receive Him, He gave the right to become children of God. You're a child of God because you received Jesus, not because you earned it." },
  { reference: "1 Corinthians 12:4-11", theme: "Gifts of the Spirit", category: "spirit", explanation: "There are different gifts, but the same Spirit gives them all. One person gets wisdom, another gets faith, another gets healing—but it's all the same Spirit working in everyone. The Spirit gives gifts not for your benefit alone, but for the common good of the body of Christ. You have spiritual gifts to serve others, not to compete with them." },
  { reference: "Matthew 7:7-14", theme: "Ask, Seek, Knock", category: "prayer", explanation: "Ask and it will be given to you; seek and you will find; knock and the door will be opened. If you, being imperfect, know how to give good gifts to your children, how much more will your Father in heaven give good gifts to those who ask? Enter through the narrow gate—the way that leads to life. God wants to give you good things; don't be afraid to ask Him." },
  { reference: "Hebrews 12:1-7", theme: "Run the Race", category: "perseverance", explanation: "You're surrounded by a cloud of witnesses who have run the race before you. Throw off everything that hinders you and run with endurance the race set before you. Fix your eyes on Jesus, who endured the cross for the joy set before Him. When you face discipline or hardship, remember that God disciplines those He loves. You're His child, and He's shaping you into who you're meant to be." },
  { reference: "Proverbs 3:9-18", theme: "The Value of Wisdom", category: "wisdom", explanation: "Honor the Lord with your wealth and the firstfruits of your harvest. Don't despise His discipline because He corrects those He loves. Wisdom is more valuable than silver or gold—nothing you desire compares to her. Wisdom brings long life, riches, honor, peace, and happiness. True wisdom comes from knowing and fearing God." },
  { reference: "Luke 15:11-24", theme: "The Prodigal Son", category: "grace", explanation: "A son took his inheritance and wasted it on wild living. When he came to his senses, he decided to return home and beg to be a servant. But his father ran to him, embraced him, and threw a party. The father didn't wait for the son to clean up first or prove himself—he ran to him while he was still far off. This is how God responds when you return to Him: with open arms, not condemnation." },
  { reference: "2 Timothy 2:1-7", theme: "Be Strong in Grace", category: "discipleship", explanation: "Be strong in the grace that is in Christ Jesus. Endure hardship like a good soldier, compete like an athlete following the rules, and work hard like a farmer. Your strength doesn't come from yourself—it comes from grace. Reflect on what Paul is saying, and the Lord will give you understanding in everything." },

  { reference: "1 Peter 2:4-10", theme: "A Chosen People", category: "identity", explanation: "You are a chosen people, a royal priesthood, a holy nation, God's special possession. You were once not a people, but now you are God's people. You were once without mercy, but now you have received mercy. You're chosen, royal, holy, and His—not because you achieved this status, but because God called you out of darkness into His light." },
  { reference: "Hebrews 4:14-16", theme: "Approach the Throne of Grace", category: "grace", explanation: "You have a great high priest in Jesus who relates to you in your weaknesses. He became human like us and was tempted in every way, just as you are, yet He never sinned. This means you can run to God's throne of grace with confidence that he wont turn you away when you need it most. Don't be afraid to come to God—He understands what you're going through and wants to help you." },
  { reference: "Psalm 139:1-12", theme: "You Know Me", category: "identity", explanation: "God knows everything about you—when you sit down, when you get up, your thoughts before you think them. He knows the inner thoughts of your heart. Where can you go from His Spirit? The reality is that we must accept that God created us to be known fully. You can't run from God. You can't be separated from His presence. He knows you completely and loves you still." },
  { reference: "John 4:7-14", theme: "Living Water", category: "jesus", explanation: "Jesus told the woman at the well that whoever drinks the water He gives will never thirst again. The water He gives becomes a spring welling up to eternal life. Physical water satisfies for a moment, but Jesus offers something that satisfies your soul forever. You don't have to keep searching for fulfillment—Jesus is the living water you've been looking for." },
  { reference: "Matthew 7:24-29", theme: "Wise and Foolish Builders", category: "teaching", explanation: "Everyone who hears Jesus' words and puts them into practice is like a wise man who built his house on rock. When the storms came, the house stood firm. The foolish man heard the words but didn't do them—his house was built on sand and collapsed. It's not enough to just hear God's Word; you have to build your life on it." },
  { reference: "James 1:2-8", theme: "Joy in Trials", category: "perseverance", explanation: "Consider it pure joy when you face trials because the testing of your faith produces perseverance. Perseverance makes you mature and complete. If you need wisdom, ask God, who gives generously without finding fault. Trials aren't fun, but they grow you. God doesn't test you to break you—He allows trials to strengthen your faith and make you complete." },
  { reference: "Proverbs 4:20-27", theme: "Guard Your Heart", category: "wisdom", explanation: "Pay attention to God's words and keep them in your heart—they are life to you. Guard your heart above all else because everything you do flows from it. Watch what you say, keep your eyes focused, and make straight paths for your feet. Your heart is the control center of your life; protect it by filling it with God's truth." },
  { reference: "2 Timothy 3:14-17", theme: "All Scripture Is God-Breathed", category: "scripture", explanation: "Continue in what you've learned from Scripture. All Scripture is God-breathed and useful for teaching, rebuking, correcting, and training in righteousness. It equips you for every good work. The Bible isn't just a history book—it's God speaking to you, shaping you, and preparing you to live the life He's called you to." },
  { reference: "1 Peter 3:13-18", theme: "Always Be Ready", category: "mission", explanation: "Who will harm you if you're eager to do good? Even if you suffer for doing right, you're blessed. Always be ready to give an answer for the hope you have, but do it with gentleness and respect. It's better to suffer for doing good than for doing evil. You don't need to be afraid of what others think—just be ready to share why Jesus gives you hope." },
  { reference: "John 14:1-7", theme: "In My Father's House", category: "hope", explanation: "Don't let your heart be troubled—trust in God and trust in Jesus. Jesus is preparing a place for you in His Father's house. You know the way to where He's going: Jesus Himself is the way, the truth, and the life. No one comes to the Father except through Him. You have a place waiting for you in heaven, and Jesus is the only way there." },

  { reference: "Ephesians 2:1-10", theme: "Made Alive in Christ", category: "grace", explanation: "You were dead in your sins, but God made you alive with Christ. It's by grace you've been saved through faith—not by works, so no one can boast. You're God's handiwork, created in Christ Jesus to do good works He prepared in advance. You're saved by grace, not by what you do—but now that you're saved, you get to do the good works God planned for you." },
  { reference: "Psalm 1:1-6", theme: "The Way of the Righteous", category: "wisdom", explanation: "Blessed is the person who doesn't walk in the counsel of the wicked or stand in the way of sinners. Instead, they delight in the law of the Lord. They're like a tree planted by streams of water, yielding fruit in season. The Lord watches over the way of the righteous, but the way of the wicked leads to destruction. Your roots go deep when you're planted in God's Word." },
  { reference: "Psalm 139:13-18", theme: "Fearfully and Wonderfully Made", category: "identity", explanation: "God created your inmost being and knit you together in your mother's womb. You're fearfully and wonderfully made—God's works are wonderful. He knew you before you were born and wrote all your days in His book. His thoughts about you outnumber the grains of sand. You're not an accident or a mistake—you're God's intentional, wonderful creation." },
  { reference: "John 6:35-40", theme: "The Bread of Life", category: "jesus", explanation: "Jesus said, \"I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.\" Everyone the Father gives to Jesus will come to Him, and He won't turn anyone away. Jesus satisfies your deepest hunger and thirst. You don't need to keep searching for fulfillment—Jesus is enough." },
  { reference: "Matthew 11:25-30", theme: "Come to Me", category: "rest", explanation: "Jesus invites you to come to Him when you're weary and burdened, and He'll give you rest. Take His yoke upon you and learn from Him—He's gentle and humble in heart. His yoke is easy and His burden is light. Jesus doesn't add more weight to your life; He invites you to rest in what He's already done." },
  { reference: "James 1:19-27", theme: "Doers of the Word", category: "obedience", explanation: "Be quick to listen, slow to speak, and slow to become angry. Don't just listen to the Word—do what it says. If you only listen and don't act, you're like someone looking in a mirror and immediately forgetting what they look like. True religion is caring for orphans and widows and keeping yourself from being polluted by the world." },
  { reference: "Psalm 119:9-16", theme: "Hidden in My Heart", category: "scripture", explanation: "How can a young person keep their way pure? By living according to God's Word. Seek God with all your heart and don't stray from His commands. Hide His Word in your heart so you won't sin against Him. Delight in His Word and don't neglect it. God's Word isn't just rules to follow—it's treasure to hide in your heart." },
  { reference: "1 Peter 1:3-9", theme: "A Living Hope", category: "hope", explanation: "Praise God! In His great mercy, He gave you new birth into a living hope through the resurrection of Jesus. You have an inheritance that can never perish, spoil, or fade—kept in heaven for you. Even though you face trials now, your faith is being refined like gold. You love Jesus even though you haven't seen Him, and you believe in Him with joy." },
  { reference: "1 Corinthians 15:51-58", theme: "Victory Over Death", category: "hope", explanation: "When the trumpet sounds, the dead will be raised imperishable, and you'll be changed. Death has been swallowed up in victory. \"Where, O death, is your victory? Where, O death, is your sting?\" Thanks be to God who gives you the victory through Jesus. Stand firm and always give yourself fully to the Lord's work—your labor is not in vain." },
  { reference: "Revelation 21:1-7", theme: "A New Heaven and Earth", category: "hope", explanation: "God will create a new heaven and a new earth. He'll dwell with His people, and there will be no more death, mourning, crying, or pain. God will wipe every tear from your eyes. He's making everything new. This world isn't the end of the story—God has something far better waiting for you." },

  { reference: "Psalm 8:1-9", theme: "The Majesty of God", category: "worship", explanation: "How majestic is God's name in all the earth! When you look at the heavens and the moon and stars, what is man that God is mindful of him? Yet You made humans a little lower than the angels and crowned them with glory and honor. God cares about you even though the universe is so vast. You matter to the Creator of everything." },
  { reference: "Psalm 19:1-11", theme: "The Heavens Declare", category: "worship", explanation: "The heavens declare the glory of God; the skies proclaim the work of His hands. Day after day they pour forth speech. God's law is perfect, refreshing the soul. His commands are radiant, giving light to the eyes. They're more precious than gold and sweeter than honey. All of creation points to God—look around and see His glory everywhere." },
  { reference: "John 10:7-15", theme: "The Good Shepherd", category: "jesus", explanation: "Jesus said, \"I am the gate for the sheep. I am the good shepherd. The good shepherd lays down his life for the sheep.\" Jesus doesn't just point the way—He is the way. He knows His sheep by name, and they know His voice. He didn't come to steal or destroy; He came to give you abundant life." },
  { reference: "Matthew 18:21-35", theme: "The Unmerciful Servant", category: "forgiveness", explanation: "Peter asked Jesus how many times he should forgive someone—seven times? Jesus said, \"Not seven times, but seventy-seven times.\" Then He told a parable about a servant who was forgiven a huge debt but refused to forgive someone who owed him a small amount. You've been forgiven an unpayable debt by God—now forgive others the way you've been forgiven." },
  { reference: "1 Peter 5:5-11", theme: "Humble Yourselves", category: "humility", explanation: "Humble yourselves under God's mighty hand, and He'll lift you up in due time. Cast all your anxiety on Him because He cares for you. The devil prowls around like a roaring lion, but resist him and stand firm in your faith. God will restore, confirm, strengthen, and establish you after you've suffered a little while. You can trust God with your worries—He actually cares about them." },
  { reference: "Psalm 119:105-112", theme: "Lamp to My Feet", category: "scripture", explanation: "God's Word is a lamp to your feet and a light for your path. It gives direction when you don't know which way to go. Though you're suffering, God revives you according to His Word. Your heart is set on keeping His decrees to the very end. The Word isn't a burden to carry—it's a light to guide you." },
  { reference: "Romans 15:4-13", theme: "The God of Hope", category: "hope", explanation: "Everything written in the past was written to teach you, so that through endurance and encouragement of the Scriptures, you might have hope. May the God of hope fill you with all joy and peace as you trust in Him. Hope doesn't come from your circumstances—it comes from God. He's the source of your hope, and His Word encourages you to keep going." },
  { reference: "Psalm 32:1-7", theme: "Blessed Is the Forgiven", category: "forgiveness", explanation: "Blessed is the one whose sins are forgiven and covered. When you confessed your sin to God, He forgave you. You're God's hiding place—He protects you from trouble and surrounds you with songs of deliverance. Don't hide your sin; confess it to God and receive His forgiveness. You're blessed not because you're perfect, but because you're forgiven." },
  { reference: "Psalm 34:1-10", theme: "Taste and See", category: "worship", explanation: "Taste and see that the Lord is good; blessed is the one who takes refuge in Him. The righteous cry out, and the Lord hears them and delivers them from all their troubles. The Lord is close to the brokenhearted. You don't have to pretend everything is fine—God is near when you're hurting, and He hears you when you cry out." },
  { reference: "Psalm 40:1-8", theme: "He Lifted Me Up", category: "praise", explanation: "I waited patiently for the Lord; He turned to me and heard my cry. He lifted me out of the mud and mire and set my feet on a rock. He put a new song in my mouth. Many will see and put their trust in the Lord. God rescued you—not because you deserved it, but because He's faithful. He gives you a new song to sing about His goodness." },
];

// ============================================
// PASSAGE OF THE DAY FUNCTIONS
// ============================================

/**
 * Get today's passage based on day of year
 * Cycles through all passages
 */
export function getPassageOfTheDay(): PassageOfTheDay {
  const today = new Date();
  const startOfYear = new Date(today.getFullYear(), 0, 0);
  const diff = today.getTime() - startOfYear.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);

  const passageIndex = (dayOfYear - 1) % PASSAGES.length;
  const passage = PASSAGES[passageIndex];

  console.log('[POTD] Day of year:', dayOfYear);
  console.log('[POTD] Passage index:', passageIndex);
  console.log('[POTD] Selected passage:', passage.reference, '-', passage.theme);

  return passage;
}

/**
 * Get explanation for a passage by reference
 */
export function getPassageExplanation(reference: string): string | null {
  const passage = PASSAGES.find(p => p.reference === reference);
  return passage ? passage.explanation : null;
}

/**
 * Get passage by reference
 */
export function getPassageByReference(reference: string): PassageOfTheDay | null {
  return PASSAGES.find(p => p.reference === reference) || null;
}

/**
 * Get USFM for a passage of the day
 */
export function getPassageUSFM(passage: PassageOfTheDay): string | null {
  const parsed = parseReferenceToUSFM(passage.reference);
  return parsed?.usfm || null;
}

/**
 * Get all passages (for browsing/testing)
 */
export function getAllPassages(): PassageOfTheDay[] {
  return PASSAGES;
}

/**
 * Get passages by category
 */
export function getPassagesByCategory(category: string): PassageOfTheDay[] {
  return PASSAGES.filter(p => p.category === category);
}
