-- Ministry Feed — post headlines
--
-- A short, quotable title per post. Generated by the AI alongside the body,
-- editable in /admin. Used as the post title on the feed, the hook line in the
-- Gloo text message, and the item headline / subject in the email digest.

alter table posts
  add column if not exists headline text;
